# This workflow deploys a new version of the plugin to WordPress.org when a new tag is pushed.
# It is intended for full plugin releases, not for manual or documentation-only updates.
# The tag must be in the format X.X.X e.g 1.1.0
name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: Deploy new tagged version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: opengraph-xyz